name = "SimpleTableaux"
uuid = "e9085da1-73a4-490e-81ec-84a93b30d531"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.0.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = "1"
LinearAlgebra = "1"
